config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/faqs' => 'faqs#index'
  get '/about' => 'pages#about', as: 'about'
  get '/terms' => 'pages#terms', as: 'terms'

  resources :tasks

end

app/models/faq.rb
class Faq < ActiveRecord::Base

end

app/models/quote.rb
class Quote < ActiveRecord::Base

end

app/models/task.rb
class Task < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController

  def index
    @faqs = Faq.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end

  def terms

  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    if @task.save
      redirect_to @task, notice: "Task was successfully created"
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path, notice: "Task was successfully updated"
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: "Task was successfully deleted"
  end

  private

  def task_params
    params.require(:task).permit(:description, :due_date)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @quotes = Quote.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/faq/index.html.erb
<% @faqs.each do |faq| %>
  <%= faq.question %>
  <%= faq.answer %>
<% end %>

app/views/faqs/index.html.erb
<h2>Frequently Asked Questions</h2>

<% @faqs.each do |faq| %>
<h4>
  <%= faq.question %>
</h4>
<p class="faq">
  <%= faq.answer %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GCamp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" <%= link_to "gCamp", root_path %></a>
      </div>
    </div>
  </nav>
  <div class="container">
    <% if notice.present? %>
    <div class="bg-success text-success text-center">
      <%= notice %>
    </div>
    <% end %>
    <%= yield %>
  </div>

  <footer class="navbar navbar-default navbar-fixed-bottom container">
    <%= link_to "About", about_path  %> |
    <%= link_to "Terms", terms_path %> |
    <%= link_to "FAQ", faqs_path %> |
    <%= link_to "Tasks", tasks_path %>
  </footer>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<div class="row">
  <div class="col-md-4">
    <%= image_tag "about_page.jpg", class: "img-responsive" %>
  </div>
  <div class="col-md-6">
    <p>We are dedicated to the makers, the creators, the risk-takers.
      We wake up in the middle of the night and furiously write down ideas about
      how to make your online life better.
    </p>
    <p>
      When we're not hard at work, we're hard at play - we're the loud ones in
      the bar, and we're always the ones shutting the place down. Human
      communication and collaboration is what drives us, and it infuses every
      feature of gCamp.
    </p>
  </div>
</div>

app/views/pages/terms.html.erb
<h1>Terms</h1>

<p>gCamp is not responsible for anything, unless it is positive</p>
<p>You may not take us to court, for anything ever.</p>

app/views/tasks/edit.html.erb
<div class="page-header">
  <h1>Edit Task</h1>
</div>

<%= form_for @task, html: {class: "form-horizontal"} do |f| %>

<div class="form-group">
  <%= f.label :description, class: "col-xs-2" %>
  <div class="col-xs-4">
    <%= f.text_field :description, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :due_date, "Due Date", class: "col-xs-2" %>
  <div class="col-xs-4">
    <%= f.date_field :due_date, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-md-10 col-md-offset-2">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", tasks_path, class: "btn btn-default" %>
  </div>
</div>

<% end %>

app/views/tasks/index.html.erb
<h1>Listing Tasks <%= link_to "New Task", new_task_path,
class: "btn btn-primary pull-right" %></h1>

<table class="table">
  <thead>
    <tr>
      <th>
        Description
      </th>
      <th>
        Due Date
      </th>
      <th>
        &nbsp;
      </th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td>
        <%= task.description %>
      </td>
      <td>
        <%= task.due_date.strftime("%m/%d/%Y") %>
      </td>
      <td class="text-right">
        <%= link_to "Show", task, class: "btn btn-success" %>
        <%= link_to "Edit", edit_task_path(task), class: "btn btn-info" %>
        <%= link_to "Delete", task, method: :delete, data: {confirm: "Are you sure?"},
         class: "btn btn-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<div class="page-header">
<h1>Create a New Task</h1>
</div>

<%= form_for @task, html: {class: "form-horizontal"} do |f| %>

<div class="form-group">
  <%= f.label :description, class: "col-xs-2" %>
  <div class="col-xs-4">
    <%= f.text_field :description, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :due_date, "Due Date", class: "col-xs-2" %>
  <div class="col-xs-4">
    <%= f.date_field :due_date, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-md-10 col-md-offset-2">
    <%= f.submit class: "btn btn-primary" %>
  </div>
</div>

<% end %>

app/views/tasks/show.html.erb
<p>
<strong>Description</strong>: <%= @task.description %>
</p>

<p>
<strong>Due Date</strong>: <%= @task.due_date.strftime("%m/%d/%Y") %>
</p>

<p>
  <%= link_to "Edit", @task %> |
  <%= link_to "Back", tasks_path %>
</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>gCamp</h1>
  <h2><small>Your life, organized.</small></h2>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <%= image_tag "bootcamp_1.jpg", class: "img-responsive" %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <%= image_tag "teamwork.jpg", class: "img-responsive" %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <%= image_tag "woman.jpg", class: "img-responsive" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-primary panel-height">
      <div class="panel-heading">
        <h3 class="panel-title">Tasks</h3>
      </div>
      <div class="panel-body">
        Grouped by projects and lists. Just they way you like 'em.
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-primary panel-height">
      <div class="panel-heading">
        <h3 class="panel-title">Documents</h3>
      </div>
      <div class="panel-body">
        <ul>
          <li>Upload</li>
          <li>Comment</li>
          <li>Revise</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-primary panel-height">
      <div class="panel-heading">
        <h3 class="panel-title">Comments</h3>
      </div>
      <div class="panel-body">
        <ul>
          <li>Comment on tasks and documents</li>
          <li>Get email notifications</li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
  <% @quotes.each do |quote| %>
  <p>
  "<%= quote.phrase %>"
</p>
<p>
<cite class="text-muted">- <%= quote.author %></cite>
</p>
<% end %>
</div>
</div>